const productData =[{
    name: "Elegant Cotton 3-Piece Suit",
    description: "Comfortable and stylish 3-piece cotton suit for casual wear.",
    category: "cotton3pc",
    price: 2500,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue", "Green"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782678/pexels-dhanno-33210484_l3bc7q.jpg",
    stock: 15,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Classic Cotton 2-Piece Set",
    description: "Soft cotton 2-piece set, perfect for daily wear.",
    category: "cotton2pc",
    price: 1800,
    sizes: ["S", "M", "L"],
    colors: ["Pink", "White", "Yellow"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782669/pexels-dhanno-19335610_fnu5h5.jpg",
    stock: 20,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Silk Party Saree",
    description: "Beautiful silk saree with golden embroidery for special occasions.",
    category: "saree",
    price: 4500,
    sizes: ["Free Size"],
    colors: ["Maroon", "Black", "Gold"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782659/pexels-goutameditz-32038882_gvm50l.jpg",
    stock: 5,
    isAvailable: true,
    fabric: "Silk"
  },
  {
    name: "Casual Printed Kurti",
    description: "Lightweight cotton kurti with attractive prints.",
    category: "kurti",
    price: 1200,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Yellow", "White"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782660/pexels-tavsiapparel-28213745_kavp6d.jpg",
    stock: 25,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Partywear Long Dress",
    description: "Elegant party dress with sequins and embroidery.",
    category: "partywear",
    price: 3500,
    sizes: ["M", "L", "XL"],
    colors: ["Red", "Purple", "Black"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782711/pexels-dhanno-19281495_sklju0.jpg",
    stock: 8,
    isAvailable: true,
    fabric: "Chiffon"
  },
  {
    name: "Floral Cotton 3-Piece Suit",
    description: "Bright floral print 3-piece suit, lightweight and comfy.",
    category: "cotton3pc",
    price: 2700,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Green", "Blue"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782720/pexels-dhanno-27603241_pt7h0m.jpg",
    stock: 12,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Simple Cotton 2-Piece Set",
    description: "Plain cotton 2-piece set for daily comfort.",
    category: "cotton2pc",
    price: 1500,
    sizes: ["S", "M", "L"],
    colors: ["White", "Beige", "Light Blue"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782670/pexels-dhanno-33300902_1_txcz7d.jpg",
    stock: 18,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Designer Party Saree",
    description: "Party saree with intricate embroidery and net fabric.",
    category: "saree",
    price: 5000,
    sizes: ["Free Size"],
    colors: ["Pink", "Golden", "Blue"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782659/pexels-artworkbyumair-15226361_oafwqc.jpg",
    stock: 6,
    isAvailable: true,
    fabric: "Net"
  },
  {
    name: "Ethnic Cotton Kurti",
    description: "Traditional cotton kurti with printed patterns.",
    category: "kurti",
    price: 1300,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "White", "Blue"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782660/pexels-tavsiapparel-28213745_kavp6d.jpg",
    stock: 22,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Evening Party Gown",
    description: "Flowy evening gown for parties and weddings.",
    category: "partywear",
    price: 4000,
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Silver", "Maroon"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782741/pexels-dhanno-19281277_tk4zbi.jpg",
    stock: 7,
    isAvailable: true,
    fabric: "Chiffon"
  },
  {
    name: "Classic Cotton 3-Piece Suit",
    description: "Soft cotton 3-piece suit for everyday wear.",
    category: "cotton3pc",
    price: 2600,
    sizes: ["S", "M", "L"],
    colors: ["White", "Blue", "Pink"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782708/pexels-dhanno-27603233_aomccd.jpg",
    stock: 14,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Elegant Cotton 2-Piece Set",
    description: "Minimalist cotton 2-piece set with comfy fit.",
    category: "cotton2pc",
    price: 1700,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Yellow", "Beige"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782663/pexels-dhanno-19589909_o1nkwn.jpg",
    stock: 19,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Wedding Party Saree",
    description: "Luxurious saree for weddings and events.",
    category: "saree",
    price: 6000,
    sizes: ["Free Size"],
    colors: ["Red", "Golden", "Pink"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782675/pexels-ashvini-bmr-285129-13433335_ltgl7d.jpg",
    stock: 4,
    isAvailable: true,
    fabric: "Silk"
  },
  {
    name: "Printed Cotton Kurti",
    description: "Casual cotton kurti with vibrant prints.",
    category: "kurti",
    price: 1250,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Yellow", "Blue", "White"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782708/pexels-dhanno-27603233_aomccd.jpg",
    stock: 24,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Partywear Gown",
    description: "Elegant gown with lace detailing.",
    category: "partywear",
    price: 3800,
    sizes: ["M", "L", "XL"],
    colors: ["Pink", "Blue", "Black"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782722/pexels-dhanno-20407196_buaqyh.jpg",
    stock: 9,
    isAvailable: true,
    fabric: "Chiffon"
  },
  {
    name: "Floral Cotton 3-Piece Suit",
    description: "Bright floral cotton 3-piece set for casual wear.",
    category: "cotton3pc",
    price: 2800,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Red", "Green"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782720/pexels-dhanno-27603241_pt7h0m.jpg",
    stock: 13,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Plain Cotton 2-Piece Set",
    description: "Basic cotton 2-piece set for comfortable wear.",
    category: "cotton2pc",
    price: 1600,
    sizes: ["S", "M", "L"],
    colors: ["White", "Blue", "Beige"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782667/pexels-dhanno-19589904_hkqpkd.jpg",
    stock: 17,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Designer Saree",
    description: "Handcrafted saree with traditional embroidery.",
    category: "saree",
    price: 5200,
    sizes: ["Free Size"],
    colors: ["Blue", "Golden", "Red"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782661/pexels-1054048-14449919_tccili.jpg",
    stock: 5,
    isAvailable: true,
    fabric: "Silk"
  },
  {
    name: "Stylish Cotton Kurti",
    description: "Trendy cotton kurti with casual prints.",
    category: "kurti",
    price: 1350,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "White", "Blue"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782760/pexels-dhanno-18977053_2_rmwdtm.jpg",
    stock: 21,
    isAvailable: true,
    fabric: "Cotton"
  },
  {
    name: "Evening Party Dress",
    description: "Chic evening dress with elegant embroidery.",
    category: "partywear",
    price: 3600,
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Silver", "Purple"],
    image: "https://res.cloudinary.com/dgla7fyit/image/upload/v1762782728/pexels-dhanno-26970930_b07cmc.jpg",
    stock: 6,
    isAvailable: true,
    fabric: "Chiffon"
  },
]


module.exports = productData